### PR TITLE
Implement NFC feature and show dynamic expiration time for invoice

### PR DESCRIPTION
**Pull request by Nodirbek75**

### CODE REVIEW

**Comment by islandbitcoin** [comment]
This should say "Flashcard not supported on this device" instead of "Bold card not supported"

Screenshot 2024-05-21 at 12 03 54 PM

**Comment by islandbitcoin** [comment]
On devices that it is working, it should say "activate Flashcard scanner"

image

**Comment by islandbitcoin** [comment]
More feedback: 
 when I scan a NFC card, I get this notification pop up
image


But then after I press ok, I get his success screen:
image

**Comment by islandbitcoin** [comment]
Last comment:

When a payment fails for "insufficient funds", the user does not get any notification or alert, the page just remains on the QR code. This should give some notification of the payment failure.

**Comment by islandbitcoin** [comment]
This would be a good alert to have - I got this from flash-mobile

image

**Comment by Nodirbek75** [comment]
> More feedback: when I scan a NFC card, I get this notification pop up image
> 
> But then after I press ok, I get this success screen: image

Did you tap nfc card after invoice is created? Didn't you tap while it is loading?

**Comment by islandbitcoin** [comment]
> > More feedback: when I scan a NFC card, I get this notification pop up image
> > But then after I press ok, I get this success screen: image
> 
> Did you tap nfc card after invoice is created? Didn't you tap while it is loading?

I tapped it long after the invoice was created.

**Comment by islandbitcoin** [comment]
Add in the same Conditional messaging as the code in https://github.com/lnflash/flash-mobile/pull/190#issuecomment-2267513848

**Comment by Nodirbek75** [comment]
@islandbitcoin I think it is ready now. Can you test and approve if it works as expected? I'll merge to main

**Review by islandbitcoin — APPROVED** [review]
long awaited 
ACK

**Pull request merged**
